name: Integration Test
on:
  []
  # schedule:
  #   - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: kieranintehdas/gha-pages-auto-publish@master
      # - name: Check outputs
      #   run: |
      #     test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"
